### ISSUE TITLE
Graphs are generated when disabled

### ISSUE THREAD

**Issue by maciej-kaznowski** [arunkumar9t2/scabbard#32]
Hi, I'm trying to publish a release of my app, but the generated graphs are ending up in the release:

gradle plugin version: `0.1.0`

root build.gradle

```
buildscript {
     ...
    dependencies {
        ...
        classpath "gradle.plugin.dev.arunkumar:scabbard-gradle-plugin:0.1.0"
        ...
    }
}
```

module build.gradle:

```
...
apply plugin: "scabbard.gradle"
...
android {
    ...
    buildTypes {
        debug {
            ...
            scabbard {
                enabled true
            }
        }
        release {
            ...
            scabbard {
                enabled false
            }
        }
    }
}
```

I also have the AS plugin installed.
The apk is built via AS (with a release build type)

I also tried with `scabbard {enabled = false}` just under the android block but that didn't fix it.
I deleted all the build folders but it regenerates them. 

Let me know if you need any more information.

**Comment by arunkumar9t2** [comment]
Currently the plugin is not Android build variant aware. So whatever configured in the `scabbard {}` applies on a project level instead of Android variant level.

However if you want to differentiate behavior you could do so controlling `enabled` property manually. One such way is to simply check for calling task name and decide if scabbard should run.

For example, the follow snippet disables scabbard for release build alone.

```groovy
scabbard {
    enabled !gradle.startParameter.toString().contains("assembleRelease")
}
```

**Comment by arunkumar9t2** [comment]
I am closing this, the solution in above comment should work, please feel free to open if you have any concerns.
