### ISSUE TITLE
Incompatible with Dagger Hilt?

### ISSUE THREAD

**Issue by NaturallyAsh** [arunkumar9t2/scabbard#54]
The graph worked very well with dagger, but I just migrated to dagger hilt and it no longer functions the same.  Will you be added support for Hilt in the future?  It seems that Hilt will become the main dagger according to Google.

**Comment by arunkumar9t2** [comment]
Hi, thanks for letting me know. I am aware of this. But the graph itself would have been generated, just that gutter icon on Android Studio would be missing, since I have not added support for it yet.

I have attached a sample in #52 and tracking this there. 

The graphs' location would be:

```
Java : build/classes/java/$sourceSet/scabbard
Kotlin : build/tmp/kapt3/classes/$sourceSet/scabbard
```

If you find any other issue such as build failure or graphs not available, please add the details in #52 . Closing this for now,
